language: android
jdk:
    - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle/caches/

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - build-tools-22.0.1
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - cd EsempioIAL

script: ./gradlew assembleDebug --stacktrace
